name: Docker Hub Publish

on:
  release:
    types: [published]
  workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Get version
      id: get_version
      run: echo "RELEASE_VERSION::$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.DOCKER_USERNAME }}/elastic-discord-webhook-proxy
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        tags: "latest,${{ env.RELEASE_VERSION }}"
